# 整个配置由 4 部分组成：
# - input: 定义 input plugin 的配置
# - filters: 定义 filters plugin 的配置，filter 用来对数据流做变更操作
# - output: 定义 output plugin 的配置
# - system: 定义系统级配置
#
# 围绕 core.Msg, 系统定义若干个 match 函数，在配置文件里使用 match 函数
# 来匹配 filter 和 output 的路由，filter/output 里的每一个 match 函数
# 都匹配才算满足匹配规则
#
name = "mysql2mysqlDemo"
version = "1.0"

[input]
type = "mysql"
mode = "stream"

[input.config]
ignore-bidirectional-data = true

[input.config.source]
host = "127.0.0.1"
username = "root"
password = ""
port = 3306

[[filters]]
type = "reject"
[filters.config]
match-schema = "test_db"
match-table = "test_table"

[[filters]]
type = "rename-dml-column"
[filters.config]
match-schema = "test"
match-table = "test_table_2"
from = ["b"]
to = ["d"]

[[filters]]
type = "delete-dml-column"
[filters.config]
match-schema = "test"
match-table = "test_table"
columns = ["e", "f"]

[[filters]]
type = "dml-pk-override"
[filters.config]
match-schema = "test"
match-table = "test_table"
id = "another_id"

[output]
type = "mysql"

[output.config]
enable-ddl = true

[output.config.target]
host = "127.0.0.1"
username = "root"
password = ""
port = 3306

[output.config.execution-engine]
use-bidirection = true

[[output.config.routes]]
match-schema = "test_db"
match-table = "test_table"
target-schema = "test_db"
target-table = "test_target_db"

[scheduler]
type = "batch-table-scheduler"
[scheduler.config]
nr-worker = 1
batch-size = 2
queue-size = 1024
sliding-window-size = 1024
